# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'museums_app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for museums_app
  pod 'Firebase/Core', '~> 5.20.2'
  pod 'Firebase/Database', '~> 5.20.2'
end

